name: CI&&CD

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      
      - name: Dependent environment
        run: |
          npm i
      - name: Compile
        run: |
          node process.js
      
      - name: Generate upload list
        id: upload_list
        run: |
          $uploadConfig = @()
          Get-ChildItem -Directory -Filter "docs*" | ForEach-Object {
            $uploadConfig += "$($_.Name) => `${{ secrets.TARGET }}/$($_.Name)"
          }
          $uploads = $uploadConfig -join "`n"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "uploads<<EOF`n$uploads`nEOF"
        shell: pwsh
      
      - name: Deploy
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATEKEY }}
          uploads: ${{ steps.upload_list.outputs.uploads }}
